#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
RUNTIME="$CONFIG_HOME/quickshell/raohane"
BIN_DIR="${HOME}/.local/bin"
SYSTEMD_DIR="$CONFIG_HOME/systemd/user"
HYPR_DIR="$CONFIG_HOME/hypr"
HYPR_SNIPPET="$HYPR_DIR/raohane.conf"
HYPR_AUTOSTART="$HYPR_DIR/raohane-autostart.conf"
RAOHANE_CONFIG="$CONFIG_HOME/raohane"
RAOHANE_CONFIG_FILE="$RAOHANE_CONFIG/config.json"
LEGACY_CONFIG_FILE="$CONFIG_HOME/illogical-impulse/config.json"

for cmd in hyprctl qs python3; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    case "$cmd" in
      hyprctl) echo "[Raohane] hyprctl not found. Install/run Hyprland first." >&2 ;;
      qs) echo "[Raohane] Quickshell command 'qs' not found. Install Quickshell first." >&2 ;;
      python3) echo "[Raohane] python3 not found. The foundation runtime requires Python 3." >&2 ;;
    esac
    exit 1
  fi
done

required_foundation=(
  "scripts/raohane"
  "modules/common"
  "modules/ii"
  "modules/raohane"
  "services"
  "panelFamilies/IllogicalImpulseFamily.qml"
  "panelFamilies/RaohaneFamily.qml"
)
missing_foundation=()
for path in "${required_foundation[@]}"; do
  [[ -e "$ROOT/$path" ]] || missing_foundation+=("$path")
done

if ((${#missing_foundation[@]})); then
  echo "[Raohane] This checkout is missing committed foundation files." >&2
  printf '  missing: %s\n' "${missing_foundation[@]}" >&2
  echo "[Raohane] Update/re-clone raohane-dots before installing." >&2
  exit 1
fi

printf '[Raohane] Installing Hyprland shell...\n'

# Stop the running shell before replacing its QML graph.
systemctl --user stop raohane.service >/dev/null 2>&1 || true

mkdir -p "$RUNTIME" "$BIN_DIR" "$SYSTEMD_DIR" "$HYPR_DIR" "$RAOHANE_CONFIG"

# First-install config migration. Do not overwrite existing Raohane user settings.
if [[ ! -f "$RAOHANE_CONFIG_FILE" ]]; then
  if [[ -f "$LEGACY_CONFIG_FILE" ]]; then
    cp -a "$LEGACY_CONFIG_FILE" "$RAOHANE_CONFIG_FILE"
    printf '[Raohane] Migrated settings from %s\n' "$LEGACY_CONFIG_FILE"
  elif [[ -f "$ROOT/defaults/config.json" ]]; then
    cp -a "$ROOT/defaults/config.json" "$RAOHANE_CONFIG_FILE"
    printf '[Raohane] Seeded settings from repository defaults.\n'
  fi
fi

# Normalize the selected family without discarding the rest of the user's JSON.
if [[ -f "$RAOHANE_CONFIG_FILE" ]]; then
  python3 - "$RAOHANE_CONFIG_FILE" <<'PY'
import json
import pathlib
import sys

path = pathlib.Path(sys.argv[1])
try:
    data = json.loads(path.read_text(encoding="utf-8"))
except (OSError, json.JSONDecodeError) as exc:
    raise SystemExit(f"[Raohane] Invalid config {path}: {exc}")

data["panelFamily"] = "raohane"
tmp = path.with_suffix(path.suffix + ".tmp")
tmp.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
tmp.replace(path)
PY
fi

# Replace runtime code. Persistent settings live separately in ~/.config/raohane.
find "$RUNTIME" -mindepth 1 -maxdepth 1 -exec rm -rf -- {} +
cp -a "$ROOT"/. "$RUNTIME"/
rm -f "$RUNTIME/install-raohane.sh"
rm -rf "$RUNTIME/.git" "$RUNTIME/.github" "$RUNTIME/upstream"

install -m 0755 "$ROOT/scripts/raohane" "$BIN_DIR/raohane"

cat > "$SYSTEMD_DIR/raohane.service" <<SERVICE
[Unit]
Description=Raohane shell for Hyprland
PartOf=graphical-session.target
After=graphical-session.target

[Service]
Type=simple
ExecStart=${BIN_DIR}/raohane run
Restart=on-failure
RestartSec=1
Environment=QT_QPA_PLATFORM=wayland

[Install]
WantedBy=default.target
SERVICE

cat > "$HYPR_SNIPPET" <<'HYPR'
# Raohane shell integration
# Managed by install-raohane.sh
exec-once = systemctl --user start raohane.service

# Raohane shell controls
bind = SUPER, R, exec, raohane launcher
bind = SUPER, escape, exec, raohane settings
bind = SUPER, C, exec, raohane control
HYPR

if [[ ! -f "$HYPR_AUTOSTART" ]]; then
  cat > "$HYPR_AUTOSTART" <<'HYPR_AUTOSTART'
# Raohane autostart
# Generated by Raohane Settings.
HYPR_AUTOSTART
fi

HYPR_MAIN="$HYPR_DIR/hyprland.conf"
SOURCE_LINE='source = ~/.config/hypr/raohane.conf'
AUTOSTART_SOURCE_LINE='source = ~/.config/hypr/raohane-autostart.conf'
if [[ -f "$HYPR_MAIN" ]]; then
  if ! grep -Fqx "$SOURCE_LINE" "$HYPR_MAIN"; then
    printf '\n# Raohane shell\n%s\n' "$SOURCE_LINE" >> "$HYPR_MAIN"
  fi
  if ! grep -Fqx "$AUTOSTART_SOURCE_LINE" "$HYPR_MAIN"; then
    printf '%s\n' "$AUTOSTART_SOURCE_LINE" >> "$HYPR_MAIN"
  fi
else
  printf '%s\n%s\n' "$SOURCE_LINE" "$AUTOSTART_SOURCE_LINE" > "$HYPR_MAIN"
fi

systemctl --user daemon-reload
systemctl --user enable raohane.service >/dev/null 2>&1 || true

if [[ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]]; then
  systemctl --user start raohane.service >/dev/null 2>&1 || true
fi

printf '\n[Raohane] Installed.\n'
printf 'Runtime: %s\n' "$RUNTIME"
printf 'Settings: %s\n' "$RAOHANE_CONFIG_FILE"
printf 'Launcher: %s\n' "$BIN_DIR/raohane"
printf 'Hyprland snippet: %s\n' "$HYPR_SNIPPET"
printf 'Autostart snippet: %s\n\n' "$HYPR_AUTOSTART"
printf 'Start now with: raohane start\n'
printf 'Debug in terminal: raohane run\n'
