#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
RUNTIME="${XDG_CONFIG_HOME:-$HOME/.config}/quickshell/raohane"
BIN_DIR="${HOME}/.local/bin"
SYSTEMD_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
HYPR_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/hypr"
HYPR_SNIPPET="$HYPR_DIR/raohane.conf"
HYPR_AUTOSTART="$HYPR_DIR/raohane-autostart.conf"
RAOHANE_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/raohane"

if ! command -v hyprctl >/dev/null 2>&1; then
  echo "[Raohane] hyprctl not found. Install/run Hyprland first." >&2
  exit 1
fi
if ! command -v qs >/dev/null 2>&1; then
  echo "[Raohane] Quickshell command 'qs' not found. Install Quickshell first." >&2
  exit 1
fi

printf '[Raohane] Installing Hyprland shell...\n'

# Stop the running shell before replacing its QML graph.
systemctl --user stop raohane.service >/dev/null 2>&1 || true

mkdir -p "$RUNTIME" "$BIN_DIR" "$SYSTEMD_DIR" "$HYPR_DIR" "$RAOHANE_CONFIG"

# Raohane owns its configuration namespace at ~/.config/raohane.

# Keep user data outside the source tree intact where possible; replace runtime code.
find "$RUNTIME" -mindepth 1 -maxdepth 1 -exec rm -rf -- {} +
cp -a "$ROOT"/. "$RUNTIME"/
rm -f "$RUNTIME/install-raohane.sh"

install -m 0755 "$ROOT/scripts/raohane" "$BIN_DIR/raohane"

cat > "$SYSTEMD_DIR/raohane.service" <<SERVICE
[Unit]
Description=Raohane shell for Hyprland
PartOf=graphical-session.target
After=graphical-session.target

[Service]
Type=simple
ExecStart=${BIN_DIR}/raohane run
Restart=on-failure
RestartSec=1
Environment=QT_QPA_PLATFORM=wayland

[Install]
WantedBy=default.target
SERVICE

cat > "$HYPR_SNIPPET" <<'HYPR'
# Raohane shell integration
# Managed by install-raohane.sh
exec-once = systemctl --user start raohane.service

# Raohane shell controls
bind = SUPER, R, exec, raohane launcher
bind = SUPER, slash, exec, raohane hotkeys
bind = SUPER, escape, exec, raohane settings
bind = SUPER, C, exec, raohane control
bind = SUPER SHIFT, M, exec, raohane media-overlay
HYPR

if [[ ! -f "$HYPR_AUTOSTART" ]]; then
  cat > "$HYPR_AUTOSTART" <<'HYPR_AUTOSTART'
# Raohane autostart
# Generated by Raohane Settings.
HYPR_AUTOSTART
fi

HYPR_MAIN="$HYPR_DIR/hyprland.conf"
SOURCE_LINE='source = ~/.config/hypr/raohane.conf'
AUTOSTART_SOURCE_LINE='source = ~/.config/hypr/raohane-autostart.conf'
if [[ -f "$HYPR_MAIN" ]]; then
  if ! grep -Fqx "$SOURCE_LINE" "$HYPR_MAIN"; then
    printf '\n# Raohane shell\n%s\n' "$SOURCE_LINE" >> "$HYPR_MAIN"
  fi
  if ! grep -Fqx "$AUTOSTART_SOURCE_LINE" "$HYPR_MAIN"; then
    printf '%s\n' "$AUTOSTART_SOURCE_LINE" >> "$HYPR_MAIN"
  fi
else
  printf '%s\n%s\n' "$SOURCE_LINE" "$AUTOSTART_SOURCE_LINE" > "$HYPR_MAIN"
fi

systemctl --user daemon-reload
systemctl --user enable raohane.service >/dev/null 2>&1 || true

if [[ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]]; then
  systemctl --user start raohane.service >/dev/null 2>&1 || true
fi

printf '\n[Raohane] Installed.\n'
printf 'Runtime: %s\n' "$RUNTIME"
printf 'Launcher: %s\n' "$BIN_DIR/raohane"
printf 'Hyprland snippet: %s\n' "$HYPR_SNIPPET"
printf 'Autostart snippet: %s\n\n' "$HYPR_AUTOSTART"
printf 'Start now with: raohane start\n'
printf 'Debug in terminal: raohane run\n'
